[package]
name = "ferris-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.92"
config = "0.15.26"
dotenvy = "0.15.7"
once_cell = "1.21.4"
reqwest = { version = "0.13.5", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["full"] }
